#!/bin/csh
# Go to home directory that own full auth
echo "Checking input ..."
if ( $?1 ) then
    echo $1
else
    echo "Inalid input argument"
endif

cd ~
set script_dir = "linux-env"

# Remove old version if exists
rm -rf ./$script_dir

# Get the latest version
echo "Clone the latest code ..."
git clone -b master https://github.com/scilabtop/linux-env.git --depth=1

# Go to the directory and install
cd ./$script_dir
chmod +x ./install

if ( -e /bin/csh ) then
    set cmd = "/bin/csh"
else if ( -e /bin/tcsh ) then
    set cmd = "/bin/tcsh"
else
    echo "csh/tcsh not installed"
endif

echo "Begin to install $cmd ..."
if ( $~cmd ) then
    $cmd ./install $1
else
    echo "something wrong with csh/tcsh"
endif

cd ..

# Clean
rm -rf ./linux-env

