#!/bin/bash
echo '=== Script: download-x86_64: Go to home directory that own full auth'
cd ~
script_dir=linux-env

echo '=== Remove old version if exists'
rm -rf ./$script_dir

echo '=== Get the latest version'
git clone https://github.com/scilabtop/linux-env.git

echo '=== Go to the directory and install'
cd ./$script_dir
chmod +x ./install-x86_64
bash ./install-x86_64
cd ..

echo '=== Clean'
rm -rf ./linux-env

echo '=== Finished'

