#!/bin/bash
cat /dev/null > ~/.cshrc_custom
cat ./csh/csh_aliases_aarch64 > ~/.cshrc_custom

#cat /dev/null > ~/.bashrc
#cat ./bash/bash_rc > ~/.bashrc

cat /dev/null > ~/.vimrc
cat ./csh/vim_rc > ~/.vimrc

cat /dev/null > ~/.ssh/config
cat ./csh/ssh_config > ~/.ssh/config
chmod 644 ~/.ssh/config


source ~/.cshrc


