#!/bin/bash
echo '+++ Script: install-x64_64'
setenv target "x86_64"

cat /dev/null > ~/.cshrc_custom
cat ./csh/csh_aliases > ~/.cshrc_custom

#cat /dev/null > ~/.bashrc
#cat ./bash/bash_rc > ~/.bashrc

cat /dev/null > ~/.vimrc
cat ./csh/vim_rc > ~/.vimrc

cat /dev/null > ~/.ssh/config
cat ./csh/ssh_config > ~/.ssh/config
chmod 644 ~/.ssh/config

cat ./csh/id_rsa.pub > ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys

# Make changes valid
source ~/.cshrc
#env=`pwd`
#bash
#cd $env
#export-libpath

echo '+++ End'


