#!/bin/bash
cat /dev/null > ~/.bash_aliases
cat ./bash/bash_aliases_aarch64 > ~/.bash_aliases

cat /dev/null > ~/.bashrc
cat ./bash/bash_rc > ~/.bashrc

cat /dev/null > ~/.vimrc
cat ./bash/vim_rc > ~/.vimrc

cat /dev/null > ~/.ssh/config
cat ./bash/ssh_config > ~/.ssh/config
chmod 644 ~/.ssh/config


source ~/.bashrc


