#!/bin/csh
echo '+++ Script: install-x64_64'
if ( $?1 ) then
    if ( $1 == "x86_64" ) then
        set target = "x86_64"
    else if ( $1 == "aarch64" ) then
        set target = "aarch64"
    endif
endif

if ( $?target ) then
    echo $target
else
    set target = "x86_64"
    echo "Invalid input, will use default x86_64"
endif

cat /dev/null > ~/.cshrc_custom
echo "set target = $target \n" > ~/.cshrc_custom
cat ./csh/csh_aliases >> ~/.cshrc_custom

cat /dev/null > ~/.bashrc
cat ./csh/bash_rc > ~/.bashrc

cat /dev/null > ~/.vimrc
cat ./csh/vim_rc > ~/.vimrc

cat /dev/null > ~/.ssh/config
cat ./csh/ssh_config > ~/.ssh/config
chmod 644 ~/.ssh/config

cat ./csh/id_rsa.pub > ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys

# Make changes valid
if ( -e ~/.cshrc ) then
    source ~/.cshrc
endif
#env=`pwd`
#bash
#cd $env
#export-libpath

echo '+++ End'
