
#!/bin/bash
cuda_ver=10.0
cuda_folder=aarch64-linux
#cuda_folder=aarch64-linux, ., 
cudnn_ver=7.2
platform=aarch64
#platform=qnx, aarch64, aarch64-android, ARMv7-android
target=aarch64
#target=x86_64, aarch64
user_home=/home/scratch.$USER_gpu
dit_dir=$user_home/p4trees/sw/sw/gpgpu/MachineLearning/DIT
trunk_dir=$dit_dir/trunk
toolkit_dir=/home/scratch.svc_compute_arch/release/cuda_toolkit
alias cd-trunk='cd $trunk_dir'

alias cd-bin='cd $trunk_dir/build/cuda-$cuda_ver/$cudnn_ver/$platform'

alias cd-scratch='cd $user_home'

alias ut-int8='./infer_test --gtest_filter=caskConvolutionTests.Int8'

alias make-tr='/usr/bin/make CUDA=cuda-$cuda_ver CUDNN=$cudnn_ver CUDA_INSTALL=$toolkit_dir/r$cuda_ver/latest -j 20 $target'

alias make-clean='/usr/bin/make clean'

alias srun-sc145='srun -w computelab-145 --pty /bin/bash'

alias cpuinfo='echo "CPU Model: "; cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c; \
echo "Physical ID: "; cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l;\
cat /proc/cpuinfo| grep "cpu cores"| uniq;\
echo "Processor: "; cat /proc/cpuinfo| grep "processor"| wc -l;\
'

alias export-libpath='export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$dit_dir/externals/cuda-$cuda_ver-$platform/$cuda_folder/lib:$dit_dir/externals/cudnn/$target/$cudnn_ver/cuda-$cuda_ver/lib64/:$dit_dir/externals/cublas-x64-linux/cuda-$cuda_ver/:$toolkit_dir/r$cuda_ver/latest/lib64/:$trunk_dir/build/cuda-$cuda_ver/$cudnn_ver/aarch64/:$dit_dir/externals/cudnn/aarch64-qnx/$cudnn_ver/cuda-$cuda_ver/lib64/:/usr/lib:/usr/lib/aarch64-linux-gnu/'

alias update-config='curl https://raw.githubusercontent.com/scilabtop/linux-env/master/download | bash'
